#!/bin/bash

usage () {
	echo "Usage: $0 <stop|containers|images|all>"
	echo "  stop       - stops running and created docker containers"
	echo "  containers - removes stopped docker containers"
        echo "  images     - removes unnamed docker images"
        echo "  all        - all of the above"
        echo "  help       - prints this message"
}

stop_containers () {
        CONTAINERS=$(docker ps -a|awk '/Up|Created /{printf("%s ", $1)}')
        if [[ -z $CONTAINERS ]]  ; then
                echo "no active or created containers found"
        else
                docker stop $CONTAINERS
        fi
}
		
remove_containers () {
	CONTAINERS=$(docker ps -a|awk '/Exited |Created /{printf("%s ", $1)}')
        if [[ -z $CONTAINERS ]]  ; then
                echo "no inactive containers found"
        else
                docker rm $CONTAINERS
        fi
}

remove_images () {
        IMAGES=$(docker images | grep none | awk '{print $3}' | sort -r)
        if [[ -z $IMAGES ]]  ; then
                echo "no unused images found"
        else
                docker rmi $IMAGES
        fi
}

if [ $# -ne 1 ]; then
        usage
        exit 1
fi

case $1 in
        stop)
                stop_containers
                ;;
        containers)
                remove_containers
                ;;
        images)
                remove_images
                ;;
        all)
                stop_containers
		remove_containers
                remove_images
                ;;
esac
